### ISSUE TITLE
Runtime Error line 487

### ISSUE THREAD

**Issue by dyeany** [PNHP/NHA_Tools#10]
Executing: CreateNHAv2 "Warrior's Path" Bedford2017 CPP_Bedford\CPP_Core CPP_Bedford\CPP_Supporting true
Start Time: Fri Oct 27 08:37:09 2017
Running script CreateNHAv2...

Tool is operating on 10 selected CPP Core(s) in layer 'CPP_Bedford\CPP_Core'
PNHP workspace: C:\Users\dyeany\AppData\Roaming\ESRI\Desktop10.5\ArcCatalog\PNHP.dyeany.pgh-gis.sde

Merging CPP Core(s) at 08:37:19
EO ID Query: "EO_ID" in (27321, 27320, 17933, 7336, 19386, 21209, 9678, 14063, 4374, 7450)

Calculating attributes for NHA Core at 08:37:21
County name(s): Bedford
USGS Quad(s): Hopewell, Saxton
Protected Land(s): Warriors Path State Park, State Game Land #73
Municipalities(s): Bedford County: Broad Top Township, Liberty Township, Saxton Borough
Old Site(s): Warriors Path Barrens, Sugar Camp Run Barrens
NHA Join ID: dly76805

Updating NHA Core layer at 08:37:36

Adding new record(s) to species table at 08:37:36

Traceback (most recent call last):
  File "<string>", line 487, in execute
RuntimeError: cannot open 'W:\Heritage\Heritage_Data\Biotics_datasets.gdb\eo_ptreps'

Failed to execute (CreateNHAv2).
Failed at Fri Oct 27 08:37:43 2017 (Elapsed Time: 34.01 seconds)

**Comment by dyeany** [comment]
Error was caused by Biotics update. Biotics geodatabase was stored at W:\Heritage\Heritage_Data\Biotics_datasets.gdb\Biotics_datasets.gdb\eo_ptreps, within a folder by the same name. 

Kierstin and @memoore resolved this issue by relocating the geodatabase. This issue should be avoided in the future to prevent errors like this.

**Comment by ChristopherTracey** [comment]
Indeed. Thanks for solving it.
