### ISSUE TITLE
exporter tool - delete fields

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/NHA_Tools#104]
@memoore,
   The new exporter tool is great! When you get a chance, can you modify the tool to delete the following fields from the Core layer and whatever subset of these fields are in the Supporting Landscape layer?

- Archive Date
- Archive Reason
- Created Date
- Created User
- Last Edited Date
- Last Edited User
- Map ID
- Notes
- Old Site Name
- Status
- Source Report
- PROJECT
- WPC Blueprint?

**Comment by memoore** [comment]
updated to exclude unwanted fields.
