### ISSUE TITLE
NHA Species Table

### ISSUE THREAD

**Issue by Anna-Johnson** [PNHP/NHA_Tools#24]
Automatically generate formatted table in report, including all species present in NHA. Steps in this section include:

1) Determining our "cut off" for species inclusion in table--S3 and higher? Which watch list species should/should not be in the table? How long ago is a siting considered still relevant? 25 years?

2) Importing appropriate symbol for each taxon 

3) Import Global and State Ranks, EO Quality, and PA Legal Status

4) Import "last seen" date, but format just as year

5) If species are sensitive, assign letter and add additional footnote to table

**Comment by ChristopherTracey** [comment]
This is fully working.
