### ISSUE TITLE
Generate Location section of NHA report

### ISSUE THREAD

**Issue by Anna-Johnson** [PNHP/NHA_Tools#27]
Pull the following information, automatically, from the NHA tables in ArcGIS:

Municipality
USGS Quad
Associated NHA's
    --are we happy with how these are determined/selected? It seems a little haphazard to me right now
Protected Lands

--I think we have decided to remove "county" from this list for V3, since that is already included in the municipality section.

**Comment by ChristopherTracey** [comment]
Were we going with "County/Municipality" instead of just "Municipality"?
