### ISSUE TITLE
Narrative - References section of NHA Report

### ISSUE THREAD

**Issue by Anna-Johnson** [PNHP/NHA_Tools#28]
Create formatted bibliography entries at the bottom of each NHA report, listing references which support the information provided within the report.

--this should be the "complete" list of references, associated with any automatically generated text fragments. Users may choose not to include all that information, and will need to manually remove the references which are not needed. 

--references will be pulled from a Zotero database, based on tags (ELCODE, habitat type)

--citation format is Conservation Biology style.

**Comment by ChristopherTracey** [comment]
This is good.

**Comment by ChristopherTracey** [comment]
So, as you know, this hasn't been working yet for the pdfs. I was just poking around and part of the problem is that `{` and `}` are special characters in latex and need to be escaped like `\{` and `\}` in the code. Currently playing around with the test site and making changes inside the sqlite db. We'll need to figure out how to do this on the parsing end of things soon.

**Comment by ChristopherTracey** [comment]
This is partially working now, at least on Chris' computer. Some notes:
- Required a complete reinstall of MikTex and there were some issues with an old version of biblatex causing issues. Anna recently reinstalled Miktex for difference reasons so this might have been solved.
- I had to make some changes in terms of escaping the citations in the db. `{}`'s do not need to be escaped anymore, but I don't think script 2 is currently writing out the citations properly.  But we may need to change this in what we write in the word doc.  _needs investigating_
- I did confirm that the 'pnhp_refs/bib' file can live on the p-drive.

**Comment by ChristopherTracey** [comment]
I suspect that this is currently working.  Some notes:
- We have to use \\parencite{} in the sqlite threats db and \parencite{} when writing in the word document.
- using \parencite*{} will cause only the year to display
- missing the reference in the master .bib file should show the code to appear, so these should be easy to troubleshoot.
