### ISSUE TITLE
narrative - photos not embedding in template

### ISSUE THREAD

**Issue by ChristopherTracey** [PNHP/NHA_Tools#49]

**Comment by ChristopherTracey** [comment]
Appears to be breaking because of spaces!

**Comment by ChristopherTracey** [comment]
It's not working better than it was. Image 2 is using the the temp code instead of the if loop, but I thin there are a few things to work out with that overall.

**Comment by Anna-Johnson** [comment]
this is still a problem. Photos are now being uploaded to a single central folder:
"P:\Conservation Programs\Natural Heritage Program\ConservationPlanning\NaturalHeritageAreas\_NHA\DraftSiteAccounts\z_Photos"

which I thought had been added into the graphics path directory, like so (line 17 of the .rnw script):
\graphicspath{ {../../z_BaseImages/}{../../z_BaseImages/EO_images/}{photos/}{../../DraftSiteAccounts/z_photos} }

**Comment by ChristopherTracey** [comment]
This doesn't seem to be an issue anymore.
