### ISSUE TITLE
the arc.data2sf function can't read projections on the NHA geodatabase

### ISSUE THREAD

**Issue by Anna-Johnson** [PNHP/NHA_Tools#68]
When I ask for the geometry parameters of the source features in script 1 (generating the word templates) at the end, starting at line 404, this is what I am seeing:
no projection information is attached to the simple feature geometry, getting this error message:

Error in bb(x = list(list(c(-202638.4088, -202616.728700001, -202474.366800001,  : 
  Current projection unknown. Please specify the projection. 

Geometry set for 91 features 
geometry type:  GEOMETRY
dimension:      XY
bbox:           xmin: -214482 ymin: 80907.04 xmax: 53262.58 ymax: 244480.9
epsg (SRID):    NA
proj4string:    NA

Not sure what the issue is with--change in structure of geodatabase?

**Comment by ChristopherTracey** [comment]
I think we're abandoning the tmap approach in favor of loading in images from the the Arc Pro map series.  If so, we should close this out.

**Comment by ChristopherTracey** [comment]
Closing as we abandoned this line of thinking.
